spring:
  application:
    name: exchange-service
  datasource:
    url: jdbc:h2:mem:exchange
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

logging:
  level:
    root: INFO

exchange:
  api:
    url: https://api.privatbank.ua
    path: /p24api/pubinfo?json
